### ISSUE TITLE
checkAlreadyLoadedNewToday doesn't seem to be working correctly

### ISSUE THREAD

**Issue by justinctlam** [SoftwareEngineeringDaily/se-daily-iOS#44] opened 2017-11-11 06:19 UTC
checkAlreadyLoadedNewToday doesn't seem to be working correctly.
Every time I launch the app, it will try to fetch data from the network and append the items to Disk.
This would increase the Disk data indefinitely. 

We also don't ever clear the data either.

**Comment by themisterholliday** [comment] 2017-11-11 17:04
I see where the issue is. I'll look into it this week.

**Comment by themisterholliday** [comment] 2017-11-21 22:02
This is fixed in #47

**Closed as completed by themisterholliday** 2017-11-21 22:02 UTC
